### ISSUE TITLE
Raid Sim Alpha Checklist

### ISSUE THREAD

**Issue by kayla-glick** [wowsims/wotlk#2366]
# Items still TODO
- [ ] Detecting party composition using auras / casts (e.g. healing stream totem and heroic presence)
- [ ] Detecting mage focus magic targets
- [ ] Detecting consumables
- [ ] Detecting paladin blessings
- [ ] Detective explosive usage
